blog/urls.py
from django.urls import path

from .views.blog import PostsGridView, PostDetailView
from .views.blog import PostCommentView, PostCommentDeleteView


urlpatterns = (
    path('', PostsGridView.as_view(), name='blog page'),
    path('<slug:slug>/', PostDetailView.as_view(), name='post detail'),
    path('comment/<slug:slug>/', PostCommentView.as_view(), name='comment post'),
    path('delete-comment/<int:pk>/', PostCommentDeleteView.as_view(), name='delete comment'),
)

realestate/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('', include('pages.urls')),
    path('listings/', include('listings.urls')),
    path('accounts/', include('accounts.urls')),
    path('contacts/', include('contacts.urls')),
    path('blog/', include('blog.urls')),
    path('sale/', include('sale.urls')),
    path('admin/', admin.site.urls),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blog/models.py
from django.contrib.auth import get_user_model
from django.db import models

UserModel = get_user_model()


class Category(models.Model):
    TITLE_MAX_LEN = 70
    title = models.CharField(
        max_length=TITLE_MAX_LEN,
    )

    class Meta:
        ordering = ['title']

    def __str__(self):
        return self.title


class Post(models.Model):
    POST_TITLE_MAX_LEN = 200
    SLUG_MAX_LEN = 200

    # Status types
    STATUS = (
        (0, "Draft"),
        (1, "Publish")
    )

    title = models.CharField(
        max_length=POST_TITLE_MAX_LEN,
        unique=True,
    )
    category = models.ForeignKey(
        Category,
        related_name='categories',
        on_delete=models.CASCADE,
    )
    slug = models.SlugField(
        max_length=SLUG_MAX_LEN,
        unique=True,
    )
    author = models.ForeignKey(
        UserModel,
        on_delete=models.CASCADE,
        related_name='blog_posts',
    )
    image = models.URLField()
    updated_on = models.DateField(
        auto_now=True,
    )
    content = models.TextField()
    created_on = models.DateField(
        auto_now_add=True,
    )
    status = models.IntegerField(
        choices=STATUS,
        default=0,
    )

    class Meta:
        ordering = ['-created_on']

    def __str__(self):
        return self.title


class Comment(models.Model):
    text = models.TextField()
    published = models.DateTimeField(auto_now_add=True,)
    post = models.ForeignKey(Post, on_delete=models.CASCADE)
    user = models.ForeignKey(
        UserModel,
        on_delete=models.CASCADE,
    )

blog/forms.py
from django import forms

from .models import Comment
from helpers.form_mixins import BootstrapFormsMixin, DisabledFieldsFormMixin


class CommentForm(forms.ModelForm, BootstrapFormsMixin):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self._init_bootstrap_form_controls()

    class Meta:
        model = Comment
        fields = ('text',)
        labels = {'text': 'Add comment'}
        widgets = {
            'text': forms.TextInput(
                attrs={'placeholder': 'Your comment...', }
            ),
        }


class DeleteCommentForm(forms.ModelForm, BootstrapFormsMixin):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self._init_bootstrap_form_controls()

    class Meta:
        model = Comment
        fields = ()

blog/views/blog.py
from django.views import generic as views
from django.contrib.auth import mixins as auth_mixins
from django.shortcuts import redirect
from django.urls import reverse_lazy
from django.views import generic as views
from ..models import Post, Comment
from ..forms import CommentForm, DeleteCommentForm

class PostsGridView(views.ListView):
    paginate_by = 3
    model = Post
    template_name = 'blog/posts_grid.html'
    context_object_name = 'posts'

    def get_queryset(self):
        return Post.objects.filter(status=1).order_by('-created_on')


class PostDetailView(views.DetailView):
    model = Post
    template_name = 'blog/post_details.html'
    context_object_name = 'post'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        post = context['post']
        comments_count = len(post.comment_set.all())

        context['comment_form'] = CommentForm(
            initial={'post_slug': self.object.slug, }
        )
        context['comments'] = post.comment_set.all()
        context.update({
            'comments_count': comments_count,
        })

        return context


class PostCommentView(auth_mixins.LoginRequiredMixin, views.View):
    permission_required = 'blog.add_comment'
    form_class = CommentForm

    def post(self, request, *args, **kwargs):
        form = self.form_class(request.POST)
        if form.is_valid():
            return self.form_valid(form)
        else:
            return self.form_invalid(form)

    def form_valid(self, form):
        post = Post.objects.get(slug=self.kwargs['slug'])
        comment = Comment(
            text=form.cleaned_data['text'],
            post=post,
            user=self.request.user,
        )
        comment.save()

        return redirect('post detail', post.slug)

    def form_invalid(self, form):
        pass


class PostCommentDeleteView(auth_mixins.LoginRequiredMixin, views.DeleteView):
    model = Comment
    form_class = DeleteCommentForm
    template_name = 'blog/delete_comment.html'

    def get_success_url(self):
        return reverse_lazy('post detail', kwargs={'slug': self.object.post.slug})

templates/blog/delete_comment.html
{% extends 'base.html' %}
{% block content %}
    <div class="container mb-5">
        <h1 class="text-center" style="padding-bottom: 20px">Are you sure you want to delete this comment?</h1>
        <div class="row">
            <div class="col-lg-3"></div>
            <div class="col-lg-6">

                <!-- Form -->
                <form method="POST" action="{% url 'delete comment' comment.pk %}">
                    {% csrf_token %}
                    {{ form }}
                    <div class="col-md-12 text-center" style="padding-top: 20px">
                        <input type="submit" value="Confirm" class="btn btn-outline-danger"/>
                        <a class="btn btn-outline-success" href="javascript:history.back()">No, go back</a>
                    </div>
                </form>
                <!-- Form -->
            </div>
            <div class="m-2">
                </div>
            <div class="col-lg-3"></div>
        </div>
    </div>


{% endblock %}

templates/blog/paginator.html
<div class="col-sm-12">
    <nav class="pagination-a">
        <ul class="pagination justify-content-end">
            <li class="page-item disabled">
            <span>
                <a class="page-link" tabindex="-1">
                    {% if page_obj.has_previous %}
                        <b><a href="?page={{ page_obj.previous_page_number }}">&laquo;</a></b>
                    {% endif %}
                </a>
            </span>
            </li>

            <li class="page-item" style="padding-right: 30px; padding-top: 15px">
                <span class="current">
            Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}.
        </span>
            </li>

            {% if page_obj.has_next %}
                <li class="page-item next">
                    <a class="page-link">
                         <span>
                             <b><a style="max-height: 50%" href="?page={{ page_obj.next_page_number }}">&raquo;</a></b>
                         </span>
                    </a>
                </li>
            {% endif %}
        </ul>
    </nav>
</div>

templates/blog/post_details.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
  <!-- Breadcrumb -->
  <section id="bc" class="mt-3">
    <div class="container">
      <nav aria-label="breadcrumb">
        <ol class="breadcrumb">
          <li class="breadcrumb-item">
            <a href="{% url 'blog' %}">
              <i class="fas fa-home"></i> Home</a>
          </li>
          <li class="breadcrumb-item active"> Blog</li>
        </ol>
      </nav>
    </div>
  </section>
    <main id="main" class="p-3">

        <!-- ======= Intro Single ======= -->
        <section class="intro-single">
            <div class="container">
                <div class="row">
                    <div class="col-md-12 col-lg-8">
                        <div class="title-single-box">
                            <h1 class="title-single">{{ post.title }}</h1>
                            <span class="color-text-a">{{ post.category }}</span>
                        </div>
                    </div>
                </div>
            </div>
        </section><!-- End Intro Single-->

        <!-- ======= Blog Single ======= -->
        <section class="news-single nav-arrow-b">
            <div class="container">
                <div class="row">
                    <div class="col-sm-12">
                        <div class="news-img-box">
                            <img style="height: 500px; object-fit: cover; width: 1500px;" src="{{ post.image }}" alt=""
                                 class="img-fluid">
                        </div>
                    </div>
                    <div class="col-md-10 offset-md-1 col-lg-8 offset-lg-2">
                        <div class="post-information">
                            <ul class="list-inline text-center color-a">
                                <li class="list-inline-item mr-2">
                                    <strong>Author: </strong>
                                    <span class="color-text-a">{{ post.author.profile.full_name }}</span>
                                </li>
                                <li class="list-inline-item">
                                    <strong>Date: </strong>
                                    <span class="color-text-a">{{ post.created_on }}</span>
                                </li>
                            </ul>
                        </div>
                        <div class="post-content color-text-a">
                            <p class="post-intro">{{ post.content }} </p>
                        </div>
                    </div>
                    <!-- ======= End Blog Single ======= -->

                    <!-- ======= Start Comment Section ======= -->
                    <div class="col-md-10 offset-md-1 col-lg-10 offset-lg-1">
                        <div class="title-box-d">
                            <h3 class="title-d">Comments ({{ comments_count }})</h3>
                        </div>
                        <div class="box-comments">

                            <ul class="list-comments" style="
                            list-style: none;">
                                {% if comments %}
                                    {% for comment in comments %}
                                        <li>
                                            <div class="comment-avatar">
                                                <img src="
                                                        {% if not comment.user.profile.image %}{% static 'img/default-image.jpg' %}{% else %}{{ comment.user.profile.image }}{% endif %}"
                                                     alt="" class="agent-avatar img-fluid">
                                            </div>
                                            <div class="comment-details">
                                                <h4 class="comment-author">{{ comment.user }}</h4>
                                                <span>{{ comment.published }}</span>
                                                <p class="comment-description">
                                                    {{ comment.text }}
                                                </p>
                                                {% if request.user == comment.user and not perms.blog.change_comment %}
                                                    <a class="btn btn-danger btn-sm mt-1 mb-1"
                                                       href="{% url 'delete comment' comment.id %}">Delete</a>
                                                {% endif %}
                                              {% if perms.blog.change_comment %}
                                                    <a class="btn btn-danger btn-sm mt-1 mb-1"
                                                       href="{% url 'delete comment' comment.id %}">Delete</a>
                                                {% endif %}
                                            </div>
                                        </li>
                                    {% endfor %}
                                {% else %}
                                    <li><h3>There are no comments for this post. </h3></li>
                                {% endif %}
                            </ul>
                                {% if request.user.is_authenticated %}
                                    <div class="box">
                                        <form method="post" action="{% url 'comment post' post.slug %}">
                                            {% csrf_token %}
                                            {{ comment_form }}
                                            <button style="margin-top:8px; margin-bottom:8px" class="btn btn-b btn-sm"
                                                    type="submit">Add
                                            </button>
                                        </form>
                                    </div>
                                {% else %}
                                    <div style="padding-bottom: 10px" class="box">
                                        <span>You must be logged in to post a comment! <a href="{% url 'login user' %}">Login</a></span>
                                    </div>
                                {% endif %}
                        </div>
                    </div>
                    <!-- ======= End Comment Section ======= -->
                </div>
            </div>
        </section><!-- End Blog Single-->

    </main><!-- End #main -->

{% endblock %}

templates/blog/posts_grid.html
{% extends 'base.html' %}
{% block content %}

  <!-- Breadcrumb -->
  <section id="bc" class="mt-3">
    <div class="container">
      <nav aria-label="breadcrumb">
        <ol class="breadcrumb">
          <li class="breadcrumb-item">
            <a href="{% url 'blog' %}">
              <i class="fas fa-home"></i> Home</a>
          </li>
          <li class="breadcrumb-item active"> Blog</li>
        </ol>
      </nav>
    </div>
  </section>
    <main id="main">
        <!-- ======= Intro Single ======= -->
        <section class="intro-single">
            <div class="container">
                <div class="row">
                    <div class="col-md-12 col-lg-8">
                        <div class="title-single-box mb-4">
                            <h1 class="title-single">News, information, analysis and more</h1>
                            <span class="color-text-a p-2">Stay tuned</span>
                        </div>
                    </div>
                </div>
            </div>
        </section><!-- End Intro Single-->

        <!-- =======  Blog Grid ======= -->
        <section class="news-grid grid">
            <div class="container">
                <div class="row">
                    {% for post in posts %}
                        <div class="col-md-4">
                            <div class="card-box-b card-shadow news-box">
                                <div class="img-box-b">
                                    <img style="height: 400px; object-fit: cover; width: 400px;" src="{{ post.image }}" alt="" class="img-b img-fluid">
                                </div>
                                <div class="card-overlay">
                                    <div class="card-header-b">
                                        <div class="card-category-b">
                                            <a href="#" class="category-b">{{ post.category }}</a>
                                        </div>
                                        <div class="card-title-b">
                                            <h2 class="title-2">
                                                <a href="{% url 'post detail' post.slug %}">{{ post.title|truncatewords:5 }}
                                                </a>
                                            </h2>
                                        </div>
                                        <div class="card-date">
                                            <span class="date-b">{{ post.updated_on }}</span>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    {% endfor %}
                </div>
                {#                <div class="row">#}
                {#                    <div class="col-sm-12">#}
                {#                        <nav class="pagination-a">#}
                {#                            <ul class="pagination justify-content-end">#}
                {#                                <li class="page-item disabled">#}
                {#                                    <a class="page-link" href="#" tabindex="-1">#}
                {#                                        <span class="bi bi-chevron-left"></span>#}
                {#                                    </a>#}
                {#                                </li>#}
                {#                                <li class="page-item">#}
                {#                                    <a class="page-link" href="#">1</a>#}
                {#                                </li>#}
                {#                                <li class="page-item active">#}
                {#                                    <a class="page-link" href="#">2</a>#}
                {#                                </li>#}
                {#                                <li class="page-item">#}
                {#                                    <a class="page-link" href="#">3</a>#}
                {#                                </li>#}
                {#                                <li class="page-item next">#}
                {#                                    <a class="page-link" href="#">#}
                {#                                        <span class="bi bi-chevron-right"></span>#}
                {#                                    </a>#}
                {#                                </li>#}
                {#                            </ul>#}
                {#                        </nav>#}
                {#                    </div>#}
                {#                </div>#}
            </div>
        </section><!-- End Blog Grid-->
    {% include 'blog/paginator.html' %}

    </main><!-- End #main -->

{% endblock %}